#!/usr/bin/bash

# Copyright (C) 2026 BitsVital LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

echo "🟢 Starting compare text file tool!" &&
echo "⭐️ Comparing ./source/source.txt against all text files in ./input/ directory." &&
uv run main.py && 
echo "✅ Comparring text files complete!" &&
echo "⭐️ Removing duplicates from ./output/output.txt!" &&
uv run remove_duplicates.py && 
echo "✅ Removing duplicates from ./output/output.txt complete!" &&
echo "⭐️ Sorting ./output/output.txt alphabetically!" &&
uv run sort_output.py
echo "✅ Sorting completed!" &&
echo "💫 Script was succesfully completed!" &&
echo "👋 Goodbye! And, have a great day!"
